// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "image1.h"

/////////////////////////////////////////////////////////////////////////////
// CImage1

IMPLEMENT_DYNCREATE(CImage1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CImage1 properties

/////////////////////////////////////////////////////////////////////////////
// CImage1 operations
